<script setup lang="ts">
import lsm from "~/assets/images/lsm.png";
import software from "~/assets/images/software.jpeg";
</script>

<template>
  <div class="p-section">
    <v-row justify="center" align="center" class="mt-16">
      <v-col lg="8">
        <v-img class="img bounce-top" max-height="400" :src="lsm"></v-img>
      </v-col>
    </v-row>
    <v-row justify="center" align="center" class="mt-10">
      <v-col lg="6">
        <div class="text-h6 text-success">Hello!</div>
        <div class="text-h2 mt-4 text-primary">
          <b> I am Ludwig Sean.</b>
        </div>
        <div class="text-h3 text-info">
          <b>I build things on the Internet. </b>
        </div>
        <div class="text-subtitle-2 mt-4">
          I'm an Experienced Software Developer with a demonstrated history of working in
          the information technology and services industry. A full stack developer with
          experience in Django, NodeJs, ExpressJs, VueJs, NuxtJs
        </div>
      </v-col>
    </v-row>
  </div>
</template>

<style scoped>
.img {
  border-radius: 5%;
}

.bounce-top {
  animation: bounce-top 10s ease-in-out infinite alternate-reverse both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-12-27 19:6:34
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@keyframes bounce-top {
  0% {
    transform: translateY(-45px);
    animation-timing-function: ease-in;
    opacity: 1;
  }
  24% {
    opacity: 1;
  }
  40% {
    transform: translateY(-24px);
    animation-timing-function: ease-in;
  }
  65% {
    transform: translateY(-12px);
    animation-timing-function: ease-in;
  }
  82% {
    transform: translateY(-6px);
    animation-timing-function: ease-in;
  }
  93% {
    transform: translateY(-4px);
    animation-timing-function: ease-in;
  }
  25%,
  55%,
  75%,
  87% {
    transform: translateY(0);
    animation-timing-function: ease-out;
  }
  100% {
    transform: translateY(0);
    animation-timing-function: ease-out;
    opacity: 1;
  }
}
</style>
