<template>
  <div class="bg-pan-left">
    <section id="home">
      <Home />
    </section>
    <section id="about">
      <About />
    </section>
    <section id="work">
      <Work />
    </section>
    <section>
      <v-footer color="#0a1930">
        <v-row justify="center" no-gutters>
          <div class="text-overline"> &copy; 2022 • Ludwig Sean Manansala • manansalaludwig@gmail.com </div>
        </v-row></v-footer
      >
    </section>
  </div>
</template>

<style scoped>
.color-change-2x {
  -webkit-animation: color-change-2x 2s linear infinite alternate both;
  animation: color-change-2x 2s linear infinite alternate both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-12-27 18:16:15
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation color-change-2x
 * ----------------------------------------
 */
@-webkit-keyframes color-change-2x {
  0% {
    background: #19dcea;
  }
  100% {
    background: #b22cff;
  }
}
@keyframes color-change-2x {
  0% {
    background: #19dcea;
  }
  100% {
    background: #b22cff;
  }
}
</style>
